name: "Setup Node.js + pnpm"
description: "..."

runs:
  using: composite
  steps:
    - name: Setup pnpm
      uses: pnpm/action-setup@v3.0.0

    - name: Setup Node.js
      uses: actions/setup-node@v4.0.2
      with:
        node-version: "lts/*"
        cache: "pnpm"

    - name: Install dependencies
      shell: bash
      run: pnpm install
