version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: react-query
    versions:
    - 3.12.0
    - 3.12.1
    - 3.13.0
    - 3.13.10
    - 3.13.4
    - 3.13.6
    - 3.6.0
    - 3.8.2
    - 3.9.6
    - 3.9.8
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
    - 12.6.3
    - 12.7.1
    - 12.7.2
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.16
    - 13.0.6
    - 13.1.1
    - 13.1.2
  - dependency-name: msw
    versions:
    - 0.26.0
    - 0.26.1
    - 0.26.2
    - 0.27.0
    - 0.27.1
    - 0.28.0
    - 0.28.1
  - dependency-name: downshift
    versions:
    - 6.1.0
    - 6.1.1
    - 6.1.2
  - dependency-name: vite
    versions:
    - 2.0.0-beta.48
    - 2.0.0-beta.60
    - 2.0.0-beta.65
    - 2.0.0-beta.69
    - 2.0.1
    - 2.0.4
    - 2.0.5
    - 2.1.2
    - 2.1.3
    - 2.1.5
  - dependency-name: "@vitejs/plugin-react-refresh"
    versions:
    - 1.1.3
    - 1.2.2
    - 1.3.1
    - 1.3.2
  - dependency-name: "@reach/tooltip"
    versions:
    - 0.13.0
    - 0.13.2
    - 0.14.0
  - dependency-name: vercel
    versions:
    - 21.2.2
    - 21.2.3
    - 21.3.1
    - 21.3.2
    - 21.3.3
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
