name: Validate

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install dependencies
        uses: ./.github/actions/pnpm-install

      - name: Lint
        run: pnpm lint

      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Run e2e tests
        run: pnpm exec playwright test

      - uses: actions/upload-artifact@v4.2.0
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
