name: Validate

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.5

      - name: Set up Node.js
        uses: ./.github/actions/setup-node

      - name: Check
        run: pnpm check

      # TODO: cache playwright
      - name: Install Playwright Browsers
        run: pnpm exec playwright install --with-deps

      - name: Build app for e2e tests
        run: pnpm build

      - name: Run e2e tests
        run: pnpm e2e

      - uses: actions/upload-artifact@v4.3.3
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
